#
# Module manifest for .ps1 files listed below. Each of these files contain a separate class.
# Generated by: Piyush Dhimate
# Generated on: 03/May/19
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule        = 'AzureAutomation.Common.psm1'

    # Loads/imports the script files
    ScriptsToProcess  = @('CommonConstants.ps1')
    
    # Version of the module. Use this to track when the module was updated.
    ModuleVersion     = '1.0'
    
    # ID used to uniquely identify this module
    GUID              = 'F6C01EA2-E55D-43AF-8A3B-463E3D5CE865'

    Description       = 'Common classes and PS functions like console outputs, error outputs etc'
    Author            = 'Piyush Dhimate'
    FunctionsToExport = @(
        'Write-ErrorOutput',
        'Copy-HashTable',
        'Clear-WhiteSpace',
        'Get-TrimmedString',
        'Search-JsonObjectInText',
        'Get-PseudoRandomId',
        'ConvertTo-NestedHashTables'
    )

    RequiredModules   = @(
    )
		
    PrivateData       = @{
    }

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}