#
# Module manifest for .ps1 files listed below. Each of these files contain a separate class.
# Generated by: Piyush Dhimate
# Generated on: 03/May/19
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule        = 'AzureAutomation.Common.psm1'

    # Version of the module. Use this to track when the module was updated.
    ModuleVersion     = '1.0'
    
    # ID used to uniquely identify this module
    GUID              = '3F6733FA-5EE7-4AF7-ACA7-7BCD119481F7'

    Description       = 'Deployment related business logic'
    Author            = 'Piyush Dhimate'
    FunctionsToExport = @(
        'Resolve-TargetAzureSubscriptionId',
        'Get-ResourceConfigs',
        'Get-ResourceRow'
    )

    RequiredModules   = @(
    )
		
    PrivateData       = @{
    }

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}